spring.application.name=coworking-service

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized
management.info.env.enabled=true

info.app.name=coworking-service
info.app.description=Microservicio de gestion de reservas de espacios de coworking